### ISSUE TITLE
English and Hindi Sources 

### ISSUE THREAD

**Issue by OshekharO** [N0-0NE-Dev/no-fasel-scrapers#6]
### Source name

Indexer

### Source link

https://indexer.is-an.app

### Other details

You can find different websites listed here which have huge movie database and have been operating since ages.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.

**Comment by abadawe-dev** [comment]
Hey @OshekharO, you have already linked me to your website in the issue you opened in the NoFasel repo and I apperciate you adding my app to the list. I am already looking at ways to scrape fmovies. Also, here is a [list](https://www.reddit.com/r/FREEMEDIAHECKYEAH/wiki/index/) of websites you can add to your website.

**Comment by OshekharO** [comment]
> Hey @OshekharO, you have already linked me to your website in the issue you opened in the NoFasel repo and I apperciate you adding my app to the list. I am already looking at ways to scrape fmovies. Also, here is a [list](https://www.reddit.com/r/FREEMEDIAHECKYEAH/wiki/index/) of websites you can add to your website.

Nope, I think this many websites are enough 😂
